name: Promote to prod

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image of frontend
        run: docker build -t caisser/fibonacci-test -f ./client/Dockerfile.dev ./client

      - name: Run unit test
        run: docker run -e CI=true caisser/fibonacci-test npm run test

      - name: Build the prod image of other services
        run: |
          docker build -t caisser/fibonacci-client ./client
          docker build -t caisser/fibonacci-nginx ./nginx
          docker build -t caisser/fibonacci-server ./server
          docker build -t caisser/fibonacci-worker ./worker

      - name: push images to Docker hub
        run: |
          docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push caisser/fibonacci-client
          docker push caisser/fibonacci-nginx
          docker push caisser/fibonacci-server
          docker push caisser/fibonacci-worker
